LittlerootTown_House_MapScripts::
	.byte 0

LittlerootTown_House_EventScript_Man::
	msgbox LittlerootTown_House_Text_DataTypeMatchups, MSGBOX_NPC
	end

LittlerootTown_House_Text_DataTypeMatchups:
	.string "A new type has been discovered\n"
	.string "recently.\p"
	.string "POKéMONs of that type are strong\n"
	.string "against mystical creatures thanks\l"
	.string "to their technologically improved.\l"
	.string "senses.\p"
	.string "Albeit they're weak to types that\n"
	.string "can overload or jam their systems.$"  
